import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("eg1.csv")
print(df.head())
print(df.info() ,"\n")
print(df.describe()) 
print(df.columns)
print(df.dtypes)       
print(df.index)
df = df.rename(columns={"Name": "Namw", "HEX": "H", "RGB": "GB"})
print(df.head(3))
df = df.set_index("Namw")
print(df.head(3))
df.columns = ["G", "B", "R"]
print(df.head(3))
print(df.sort_values(by="R").head(3))
# condition wouldnt work cause 'G' is in string print(df[df["G"] > 100].head(3))
print(df[df["G"] == "#008000"])
print(df[df["G"] != "#008000"])
# converting string to numeric values , errors='coerce' will convert invalid parsing to NaN   
df["R"] = pd.to_numeric(df["R"], errors='coerce')
print(df.dtypes)    
print(df)
print(df[df["R"] > 10].head(5))
plt.bar(df["G"].head(5), df["R"].head(5), color='green')
plt.xlabel("Color Names")
plt.ylabel("R values")
plt.title("Bar Plot of R values")
plt.show()
# saving modified dataframe to new csv file  ;  df.to_csv("modified_colors.csv")
plt.bar(df.index , df["R"], color='blue')
plt.xlabel("Color Names")
plt.ylabel("R values")
plt.title("Bar Plot of R values for all colors")
plt.show() 
print(df.sort_values(by="R", ascending=False))
# printing index of max and min value in R column
print(df['R'].idxmax())
print(df['R'].idxmin())
dff = pd.DataFrame(index=df.index)
dff['R1'] = df['R']
print(dff)
dff.plot(kind='bar', color='red')
plt.xlabel("Color Names")
plt.ylabel("R1 values") 
plt.title("Bar Plot of R1 values")
plt.show()
dff.plot(figsize=(10, 5))
plt.xlabel("Color Names")
plt.ylabel("R1 values")
plt.title("Line Plot of R1 values")
plt.show()
dff.to_csv("eg1newly saved.csv")
dff.loc['Red': 'Purple'].plot(kind='bar', color='orange')
plt.xlabel("Color Names")
plt.ylabel("R1 values") 
plt.title("Bar Plot of R1 values from Red to purple")
plt.show()
dff.loc['Red': 'Purple'].plot(figsize=(10, 5))
plt.xlabel("Color Names")
plt.ylabel("R1 values") 
plt.title("Bar Plot of R1 values from Red to purple")
plt.show()
